/**
 * 作    者：StampGIS Team
 * 创建日期：2017年9月20日
 * 描    述：菜单配置文件
 * 遗留bug ：无
 * 修改日期：2017年11月7日
 **************************************************/
var cpPs = cpPs||{};
cpPs.config =  {
    "menu":
    [
        {
            "id":"common",
            "name":"浏览",
            "title":"浏览",
            "tag":"01",
            "src":"images/top/inactiveIcons/common.png",
            "item":
            [
                {
                    "name":"飞行路径",
                    "title":"飞行路径",
                    "tag":"0102",
                    "id":"ViewFlyMode",
                    "src":"images/tools/ViewFlyMode.png"
                },{
                    "name":"人车漫游",
                    "title":"人车漫游",
                    "tag":"0103",
                    "id":"ViewPersonMode",
                    "src":"images/tools/ViewPersonMode.png"
                },
                {
                    "name":"视点管理",
                    "title":"视点管理",
                    "tag":"0104",
                    "id":"ViewPointManagement",
                    "src":"images/tools/ViewPointManagement.png"
                },{
                    "name":"快速定位",
                    "title":"快速定位",
                    "tag":"0105",
                    "id":"ViewQuickLocate",
                    "src":"images/tools/ViewQuickLocate.png"
                },{
                    "name":"屏幕截图",
                    "title":"屏幕截图",
                    "tag":"0106",
                    "id":"ViewScreenShot",
                    "src":"images/tools/ViewScreenShot.png"
                },{
                    "name":"2.5D出图",
                    "title":"2.5D出图",
                    "tag":"0107",
                    "id":"ViewPictures",
                    "src":"images/tools/ViewPictures.png"
                },{
                    "name":"二维地图",
                    "title":"二维地图",
                    "tag":"0108",
                    "id":"ViewFullScreen2D",
                    "src":"images/tools/ViewFullScreen2D.png"
                },{
                    "name":"二维鹰眼",
                    "title":"二维鹰眼",
                    "tag":"0109",
                    "id":"ViewHawkEye",
                    "src":"images/tools/ViewHawkEye.png"
                },{
                    "name":"管线更新",
                    "title":"管线更新",
                    "tag":"0110",
                    "id":"ViewPipelineUpdate",
                    "src":"images/tools/AnalysisPipelineUpdate.png"
                },{
                    "name":"显示路名",
                    "title":"显示路名",
                    "tag":"0111",
                    "id":"ViewRoadName",
                    "src":"images/tools/ViewRoadName.png"
                },{
                    "name":"流向显示",
                    "title":"流向显示",
                    "tag":"0112",
                    "id":"AnalysisFlowShowing",
                    "src":"images/tools/AnalysisFlowShowing.png"

                },{
                    "name":"剖切分析",
                    "title":"剖切分析",
                    "tag":"0113",
                    "id":"ViewClipScene",
                    "src":"images/tools/ViewClipScene.png"

                },{
                    "name":"颜色显示",
                    "title":"颜色显示",
                    "tag":"0114",
                    "id":"ViewShowing",
                    "src":"images/tools/ViewMaterialShowing.png"
                },{
                    "name":"显示图例",
                    "title":"显示图例",
                    "tag":"0115",
                    "id":"ViewLegendShowing",
                    "src":"images/tools/ViewLegendShowing.png"
                },{
                    "name":"系统设置",
                    "title":"系统设置",
                    "tag":"0116",
                    "id":"ViewSystemSetting",
                    "src":"images/tools/ViewSystemSetting.png"
                }
            ]
        },
        {
            "id":"query",
            "name":"查询",
            "title":"查询",
            "tag":"02",
            "src":"images/top/inactiveIcons/query.png",
            "item":
            [
                {
                    "name":"空间查询",
                    "title":"空间查询",
                    "tag":"0201",
                    "id":"QuerySpatial",
                    "src":"images/tools/QuerySpatial.png"

                },
                {
                    "name":"缓冲查询",
                    "title":"缓冲查询",
                    "tag":"0202",
                    "id":"QueryBuffer",
                    "src":"images/tools/QueryBuffer.png"
                },
                {
                    "name":"特征查询",
                    "title":"特征查询",
                    "tag":"0203",
                    "id":"QueryEquipment",
                    "src":"images/tools/QueryEquipment.png"
                },
                {
                    "name":"附属查询",
                    "title":"附属查询",
                    "tag":"0204",
                    "id":"QueryAttachment",
                    "src":"images/tools/QueryAttachment.png"
                },
                {
                    "name":"管径查询",
                    "title":"管径查询",
                    "tag":"0205",
                    "id":"QuerySquareness",
                    "src":"images/tools/QuerySquareness.png"
                },
                {
                    "name":"材质查询",
                    "title":"材质查询",
                    "tag":"0206",
                    "id":"QueryMaterial",
                    "src":"images/tools/QueryMaterial.png"
                },
                {
                    "name":"废弃查询",
                    "title":"废弃查询",
                    "tag":"0207",
                    "id":"QueryAbandon",
                    "src":"images/tools/QueryAbandon.png"
                },
                {
                    "name":"权属查询",
                    "title":"权属查询",
                    "tag":"0208",
                    "id":"QueryOwner",
                    "src":"images/tools/QueryOwner.png"
                },
                {
                    "name":"道路查询",
                    "title":"道路查询",
                    "tag":"0209",
                    "id":"QueryRoad",
                    "src":"images/tools/QueryRoad.png"

                },
                {
                    "name":"交叉口查询",
                    "title":"交叉口查询",
                    "tag":"0212",
                    "id":"QueryCross",
                    "src":"images/tools/QueryCross.png"

                },
                {
                    "name":"关联查询",
                    "title":"关联查询",
                    "tag":"0213",
                    "id":"QueryAssociated",
                    "src":"images/tools/QueryAssociated.png"
                },{
                    "name":"SQL查询",
                    "title":"SQL查询",
                    "tag":"0214",
                    "id":"QueryComplex",
                    "src":"images/tools/QueryComplex.png"
                }
            ]
        },
        {
            "id":"statistics",
            "name":"统计",
            "title":"统计",
            "tag":"03",
            "src":"images/top/inactiveIcons/statistics.png",
            "item":
            [
                {
                    "name":"管径分段",
                    "title":"管径分段",
                    "tag":"0301",
                    "id":"StatisticsDiameter",
                    "src":"images/tools/StatisticsDiameter.png"
                },
                {
                    "name":"埋深分段",
                    "title":"埋深分段",
                    "tag":"0302",
                    "id":"StatisticsCoveringDepth",
                    "src":"images/tools/StatisticsCoveringDepth.png"
                },
                {
                    "name":"特征分类",
                    "title":"特征分类统计",
                    "tag":"0303",
                    "id":"StatisticsEquipmentClass",
                    "src":"images/tools/StatisticsEquipmentClass.png"
                },
                {
                    "name":"附属分类",
                    "title":"附属物分类统计",
                    "tag":"0304",
                    "id":"StatisticsAttachmentClass",
                    "src":"images/tools/StatisticsAttachmentClass.png"
                },
                {
                    "name":"管径分类",
                    "title":"管径分类统计",
                    "tag":"0305",
                    "id":"StatisticsDiameterClass",
                    "src":"images/tools/StatisticsDiameterClass.png"
                },
                {
                    "name":"材质分类",
                    "title":"材质分类统计",
                    "tag":"0306",
                    "id":"StatisticsMaterialClass",
                    "src":"images/tools/StatisticsMaterialClass.png"
                },
                {
                    "name":"废弃统计",
                    "title":"废弃统计",
                    "tag":"0307",
                    "id":"StatisticsAbandon",
                    "src":"images/tools/StatisticsAbandon.png"
                },
                {
                    "name":"权属统计",
                    "title":"权属统计",
                    "tag":"0308",
                    "id":"StatisticsOwner",
                    "src":"images/tools/StatisticsOwner.png"
                },
                {
                    "name":"埋设统计",
                    "title":"埋设统计",
                    "tag":"0309",
                    "id":"StatisticsInbuilt",
                    "src":"images/tools/StatisticsInbuilt.png"
                },
                {
                    "name":"道路统计",
                    "title":"道路统计",
                    "tag":"0310",
                    "id":"StatisticsRoad",
                    "src":"images/tools/StatisticsRoad.png"
                },
                {
                    "name":"行政统计",
                    "title":"行政区统计",
                    "tag":"0311",
                    "id":"StatisticsCanton",
                    "src":"images/tools/StatisticsCanton.png"
                }
            ]
        },
        {
            "id":"analysis",
            "name":"分析",
            "title":"分析",
            "tag":"04",
            "src":"images/top/inactiveIcons/analysis.png",
            "item":
            [
                {
                    "name":"水平净距",
                    "title":"水平净距分析",
                    "tag":"0401",
                    "id":"AnalysisHorizontalDis",
                    "src":"images/tools/AnalysisHorizontalDis.png"
                },
                {
                    "name":"垂直净距",
                    "title":"垂直净距分析",
                    "tag":"0402",
                    "id":"AnalysisVerticalDis",
                    "src":"images/tools/AnalysisVerticalDis.png"
                },
                {
                    "name":"碰撞分析",
                    "title":"碰撞分析",
                    "tag":"0403",
                    "id":"AnalysisCollision",
                    "src":"images/tools/AnalysisCollision.png"
                },
                {
                    "name":"覆土分析",
                    "title":"覆土分析",
                    "tag":"0404",
                    "id":"AnalysisCoveringDepth",
                    "src":"images/tools/AnalysisCoveringDepth.png"
                },
                {
                    "name":"纵断面",
                    "title":"纵断面分析",
                    "tag":"0405",
                    "id":"AnalysisVerSection",
                    "src":"images/tools/AnalysisVerSection.png"
                },
                {
                    "name":"横断面",
                    "title":"横断面分析",
                    "tag":"0406",
                    "id":"AnalysisTranSection",
                    "src":"images/tools/AnalysisTranSection.png"
                },
                {
                    "name":"爆管分析",
                    "title":"爆管分析",
                    "tag":"0407",
                    "id":"AnalysisBurst",
                    "src":"images/tools/AnalysisBurst.png"
                },
                {
                    "name":"追踪分析",
                    "title":"追踪分析",
                    "tag":"0408",
                    "id":"AnalysisTracking",
                    "src":"images/tools/AnalysisTracking.png"
                },
                {
                    "name":"连通分析",
                    "title":"连通分析",
                    "tag":"0409",
                    "id":"AnalysisConnective",
                    "src":"images/tools/AnalysisConnective.png"
                },
                {
                    "name":"设施搜索",
                    "title":"设施搜索",
                    "tag":"0411",
                    "id":"AnalysisAttachmentSearch",
                    "src":"images/tools/AnalysisAttachmentSearch.png"
                },
                {
                    "name":"开挖分析",
                    "title":"开挖分析",
                    "tag":"0412",
                    "id":"AnalysisExcava",
                    "src":"images/tools/AnalysisExcava.png"
                },
                {
                    "name":"预警分析",
                    "title":"预警分析",
                    "tag":"0413",
                    "id":"AnalysisWarning",
                    "src":"images/tools/AnalysisWarning.png"
                },
                {
                    "name":"管理区监测",
                    "title":"管理区监测",
                    "tag":"0414",
                    "id":"AnalysisManagerRange",
                    "src":"images/tools/AnalysisManagerRange.png"
                },
                {
                    "name":"保护区监测",
                    "title":"保护区监测",
                    "tag":"0415",
                    "id":"AnalysisProtectRange",
                    "src":"images/tools/AnalysisProtectRange.png"
                }
            ]
        },
        {
            "id":"measure",
            "name":"量算",
            "title":"量算",
            "tag":"05",
            "src":"images/top/inactiveIcons/measure.png",
            "item":
            [
                {
                    "name":"忽略地形",
                    "title":"忽略地形",
                    "tag":"0501",
                    "id":"MeasureBTerrain",
                    "src":"images/tools/MeasureBTerrain.png"
                },
                {
                    "name":"水平距离",
                    "title":"水平距离",
                    "tag":"0502",
                    "id":"MeasureHorizontalDis",
                    "src":"images/tools/MeasureHorizontalDis.png"
                },
                {
                    "name":"垂直距离",
                    "title":"垂直距离",
                    "tag":"0503",
                    "id":"MeasureVerticalDis",
                    "src":"images/tools/MeasureVerticalDis.png"
                },
                {
                    "name":"空间距离",
                    "title":"空间距离",
                    "tag":"0504",
                    "id":"MeasureSpaceDis",
                    "src":"images/tools/MeasureSpaceDis.png"
                },
                {
                    "name":"面积测量",
                    "title":"面积测量",
                    "tag":"0505",
                    "id":"MeasureFlatArea",
                    "src":"images/tools/MeasureFlatArea.png"
                },
                {
                    "name":"角度测量",
                    "title":"角度测量",
                    "tag":"0506",
                    "id":"MeasurePlaneAngle",
                    "src":"images/tools/角度测量.png"
                },
                {
                    "name":"水平间距",
                    "title":"水平间距",
                    "tag":"0507",
                    "id":"MeasurePipelineHorDis",
                    "src":"images/tools/MeasurePipelineHorDis.png"
                },
                {
                    "name":"垂直间距",
                    "title":"垂直间距",
                    "tag":"0508",
                    "id":"MeasurePipelineVerDis",
                    "src":"images/tools/MeasurePipelineVerDis.png"
                },
                {
                    "name":"空间间距",
                    "title":"空间间距",
                    "tag":"0509",
                    "id":"MeasurePipelineSpaceDis",
                    "src":"images/tools/MeasurePipelineSpaceDis.png"
                }
            ]
        },
        {
            "id":"mark",
            "name":"标注",
            "title":"标注",
            "tag":"06",
            "src":"images/top/inactiveIcons/mark.png",
            "item":
            [
                {
                    "name":"高程标注",
                    "title":"高程标注",
                    "tag":"0601",
                    "id":"MarkedElevation",
                    "src":"images/tools/MarkedElevation.png"
                },
                {
                    "name":"管径标注",
                    "title":"管径标注",
                    "tag":"0602",
                    "id":"MarkedDiameter",
                    "src":"images/tools/MarkedDiameter.png"
                },
                {
                    "name":"埋深标注",
                    "title":"埋深标注",
                    "tag":"0603",
                    "id":"MarkedCoveringDepth",
                    "src":"images/tools/MarkedCoveringDepth.png"
                },
                {
                    "name":"坐标标注",
                    "title":"坐标标注",
                    "tag":"060104",
                    "id":"MarkedCoordinates",
                    "src":"images/tools/MarkedCoordinates.png"
                },
                {
                    "name":"坡度标注",
                    "title":"坡度标注",
                    "tag":"0605",
                    "id":"MarkedSlope",
                    "src":"images/tools/MarkedSlope.png"
                },
                {
                    "name":"弯头标注",
                    "title":"弯头标注",
                    "tag":"0606",
                    "id":"MarkedCurvedAngle",
                    "src":"images/tools/MarkedCurvedAngle.png"
                },
                {
                    "name":"栓点标注",
                    "title":"栓点标注",
                    "tag":"0607",
                    "id":"MarkedAngleAndLength",
                    "src":"images/tools/MarkedAngleAndLength.png"
                },
                {
                    "name":"扯旗标注",
                    "title":"扯旗标注",
                    "tag":"0608",
                    "id":"MarkedComplex",
                    "src":"images/tools/MarkedComplex.png"
                },
                {
                    "name":"自定义标注",
                    "title":"自定义标注",
                    "tag":"0609",
                    "id":"MarkedCustomPart",
                    "src":"images/tools/MarkedCustomPart.png"
                },
                {
                    "name":"标注管理",
                    "title":"标注管理",
                    "tag":"0610",
                    "id":"MarkedManagement",
                    "src":"images/tools/MarkedManagement.png"
                }
            ]
        }
    ]
}
